### ISSUE TITLE
Name "HLA" is already in use

### ISSUE THREAD

**Issue by TheWitheredStriker** [pepsipu/hla#1]
Hello, I apologize for having to point this out, but the name "High Level Assembly" and its abbreviation "HLA" are already in use for an existing, more used and much more feature-rich high-level assembler developed by Randall Hyde: https://en.wikipedia.org/wiki/High_Level_Assembly

Hyde's HLA was written in the early 2000's and was already covered in books as early as 2005, so it predates your HLA by over a decade. To avoid confusion, it might be a good idea to rename your project. I apologize once more for the incovenience and wish you the best of luck with this assembler.

**Comment by pepsipu** [comment]
Hi! I'm well aware, this project is _so_ old and defuct. It's been superseded by https://github.com/pepsipu/aski so maybe check that out :)

**Comment by TheWitheredStriker** [comment]
Ah, I see! Interesting, I'll check that one out for sure :) good luck with it and have an awesome rest of your day!
